### ISSUE TITLE
Feature Request: Use an existing shopping list

### ISSUE THREAD

**Issue by Pezmc** [kevdliu/hacs-anylist#22]
This integration appears to always create new entities in home assistant, even if there is already a list with the same name:

```
todo.shopping_list
  friendly_name: Shopping List
  supported_features: 15
```

```
todo.shopping_list_2
  source_name: Shopping List
  checked_items:
    - Almond Milk
  unchecked_items:
    - Apple Cider Vinegar
  friendly_name: Shopping List
  supported_features: 71
```

Is there any way to have the integration use the existing shopping list entity? This is created by default with a HA instance.

Asking as I'd love to be able to synchronise the `todo.shopping_list` across different services e.g. Alexa & Anylist via Home Assistant

Right now I just end up with two lists:
 - Alexa Integration syncing to the original home assistant todo.shopping_list
 - And this integration creating a new list with the same name

<img width="427" alt="Image" src="https://github.com/user-attachments/assets/bf0797a9-d3fb-43b5-9e3f-c4a0c144019a" />
